# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

name: Terraform modules release
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"
  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  terraform:
    uses: canonical/operator-workflows/.github/workflows/terraform_modules_release.yaml@727b9ec14b6f3a5aa3e03a3cbac0fefe100a3251  # main
    permissions:
      contents: write
